### ISSUE TITLE
无意间搜索到，太强了。

### ISSUE THREAD

**Issue by barnett2010** [muchenhen/MuQianQiu#3]
大佬，有没有双击就能玩的exe版本？

**Comment by muchenhen** [comment]
我要重做成3D版本了，桥豆麻袋啊

**Comment by muchenhen** [comment]
https://github.com/muchenhen/MuQianQiu/releases 这里是之前的一些release版本= =有bug

**Comment by barnett2010** [comment]
感谢。
@muchenhen 我之前解包过，卡牌图下载https://www.aliyundrive.com/s/uVSnDxochp3
