### ISSUE TITLE
请问有发布web版本吗？

### ISSUE THREAD

**Issue by shelfofclub** [muchenhen/MuQianQiu#31]
首先，感谢复现千秋戏并一直维护！
我看到最新的release已经是很久之前的了。有发布新版的计划吗？release中也没web版本，看到github action中有godot的编译，我不懂游戏的开发，不知能否考虑用github action自动化编译godot的版本？虚幻好像也有action，不过不知道这些action能否正常适用。
再次感谢一直维护开发，之前一直使用bubububaoshe的版本，存在一些功能未能实现，但作者可能因故不再维护了，发现这个项目实在令人惊喜

**Comment by muchenhen** [comment]
有 在做了（bushi），目前在用Godot制作来支持web版本，还没有完成，不过有在推进，可以查看commit相关，另外忽悠了一个人来帮我一起，目前计划是农历春节前发布一个版本。因为没有频繁做版本的需求，感觉用不上CI流程，手动推送是足够的。感谢关注嗷~

**Comment by shelfofclub** [comment]
感谢感谢！不好意思，我不会游戏开发，只会基础的C/C++和python，帮不上忙。

另外想问下，看到这个有参考bubububaoshe的实现，那个项目我遇到一些问题，但那位作者没有继续开发了，想在这里请教一下：

1. 那个是不是没有二周目开启的弃牌功能？似乎只有鼠标左键单击一种操作，没找到弃牌的功能
2. 有时候见到AI的牌从左上角（不知是已配对的牌，还是手牌）进入公共区，公共区一张牌进入AI那里。不知这个功能是没有匹配季节的换牌，还是二周目开放的弃牌哦功能？
3. 珍稀牌的技能是不是必须使用，例如陵越的换牌，古剑三中可以通过退出界面，放弃使用技能，留住陵越，而那个项目中好像只能必须使用技能

如果您了解那个项目，方便的话能否解答一下

**Comment by muchenhen** [comment]
1.  是的 目前完全没考虑弃牌或者古网的操作逻辑。主要原因是我比较懒惰……以及我更喜欢纯随机短平快来一局的感觉，后面会考虑补充的
2. 嘶，可能是bug，我需要再看看
3. 会允许放弃使用技能，比如你提到的交换对方手牌，如果不允许放弃使用的话有些情况下这个技能是完全的副作用

**Comment by shelfofclub** [comment]
> 目前完全没考虑弃牌或者古网的操作逻辑

哈哈哈哈，感谢回复。我只玩了古剑三的一周目，对于古网或者木语人中的机制，我也不了解，感觉古剑三一周目的一代二代牌组就已经很好玩了

刚才看了下python的代码，也没找到能帮上忙的地方。回头我再看看其他代码，看看能否帮把手。
